import { CONFIGURATION_MILESTONE_IDS } from "./operationalTasksConfigurationTypes.js";

/** Ordem canônica do onboarding bloqueante no painel (S1.09 — sem M6). */
export const CONFIGURATION_MILESTONE_PRESENTATION_ORDER = [
  CONFIGURATION_MILESTONE_IDS.COMPANY_DATA,
  CONFIGURATION_MILESTONE_IDS.LEGAL_ACCEPTANCE,
  CONFIGURATION_MILESTONE_IDS.TAX_RATE,
  CONFIGURATION_MILESTONE_IDS.OPERATIONAL_COST,
  CONFIGURATION_MILESTONE_IDS.OPERATIONAL_CYCLE,
];
