import { SELLER_TOOLBOX_RECALCULATE_CONSUMPTION_ACTION_ID } from "./sellerToolboxRecalculateConsumptionOperation";
import { SELLER_TOOLBOX_RESET_CONSUMPTION_ACTION_ID } from "./sellerToolboxResetConsumptionOperation";

export const SELLER_TOOLBOX_CONSUMPTION_OPERATION_ACTION_IDS = [
  SELLER_TOOLBOX_RESET_CONSUMPTION_ACTION_ID,
  SELLER_TOOLBOX_RECALCULATE_CONSUMPTION_ACTION_ID,
];
