// Constantes espelhadas — valores vêm do backend em runtime
export const BILLING_TRIAL_STATE = {
  NOT_STARTED: "NOT_STARTED",
  ELIGIBLE: "ELIGIBLE",
  ACTIVE: "ACTIVE",
  ENDING_SOON: "ENDING_SOON",
  ENDS_TODAY: "ENDS_TODAY",
  CONVERTED: "CONVERTED",
  EXPIRED: "EXPIRED",
  REVOKED: "REVOKED",
};

/** Estados canônicos do ciclo — SSOT no backend (S1.HF.6.9A.11). */
export const BILLING_TRIAL_LIFECYCLE_STATE = {
  TRIAL_ACTIVE: "TRIAL_ACTIVE",
  TRIAL_ENDING_D3: "TRIAL_ENDING_D3",
  TRIAL_ENDING_D2: "TRIAL_ENDING_D2",
  TRIAL_ENDING_D1: "TRIAL_ENDING_D1",
  TRIAL_EXPIRED_RESTRICTED: "TRIAL_EXPIRED_RESTRICTED",
  PAID_ACTIVE: "PAID_ACTIVE",
};
