// ======================================================
// ICON REGISTRY: S7
// Objetivo:
// - Centralizar o mapeamento de ícones do Design System
// ======================================================

import {
  LayoutDashboard,
  Box,
  Tag,
  Calculator,
  Activity,
  BarChart3,
  FileText,
  Download,
  Copy,
  ExternalLink,
  GripVertical,
  Trash2,
  Info,
  Plus,
  Image as ImageIcon,
  Inbox,
  LayoutGrid,
  CircleAlert,
  Percent,
  Flame,
  CircleDollarSign,
  PackageX,
  Boxes,
  MegaphoneOff,
  Store,
  Megaphone,
  Receipt,
  TriangleAlert,
  Sparkles,
  LineChart,
  TrendingUp,
  TrendingDown,
  Truck,
  Clock,
  RotateCcw,
  Search,
  Filter,
  X,
  Eye,
  Pencil,
  CheckCircle2,
  Shield,
  Lock,
  Layers,
  Zap,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CalendarDays,
  Medal,
  Trophy,
} from "lucide-react";

export const iconsMap = {
  dashboard: LayoutDashboard,
  products: Box,
  ads: Tag,
  pricing: Calculator,
  monitoring: Activity,
  reports: BarChart3,
  records: FileText,

  download: Download,
  copy: Copy,
  external: ExternalLink,
  reorder: GripVertical,
  trash: Trash2,
  info: Info,
  plus: Plus,
  image: ImageIcon,
  empty: Inbox,

  /** Catálogo de produtos — barra de filtros (lucide, traço leve no JSX) */
  catalog_filter_all: LayoutGrid,
  catalog_filter_loss: CircleAlert,
  catalog_filter_low_margin: Percent,
  catalog_filter_top_sales: Flame,
  catalog_filter_top_profit: CircleDollarSign,
  catalog_filter_no_sales: PackageX,
  catalog_filter_low_stock: Boxes,
  catalog_filter_no_ads: MegaphoneOff,
  catalog_filter_mkt: Store,
  catalog_filter_with_ads: Megaphone,
  catalog_filter_with_sales: Receipt,
  catalog_filter_attention: TriangleAlert,
  /** Alias pedido pelo DS / prompts (lucide: TriangleAlert) */
  AlertTriangle: TriangleAlert,
  catalog_filter_opportunity: Sparkles,
  catalog_filter_declining: LineChart,
  /** Tendência / crescimento — acento visual executivo */
  trend_up: TrendingUp,
  trend_down: TrendingDown,
  truck_shipping: Truck,
  catalog_filter_new: Clock,
  /** Anúncios — filtro por volume de visitas */
  ads_filter_visits: Eye,
  filter_clear: RotateCcw,
  filter: Filter,
  search: Search,
  chevron_down: ChevronDown,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  calendar: CalendarDays,
  close: X,
  edit: Pencil,

  /** Billing — timeline e experiência financeira (Fase 3.0.3) */
  billing_check: CheckCircle2,
  billing_alert: CircleAlert,
  billing_refresh: RotateCcw,
  billing_shield: Shield,
  billing_bolt: Zap,
  billing_clock: Clock,
  billing_lock: Lock,
  billing_layers: Layers,
  billing_payment: Receipt,
  billing_money: CircleDollarSign,

  /** Mercado Livre — reputação do vendedor (MercadoLíder) */
  mercado_lider_medal: Medal,

  /** Pódio executivo — Top 10 Vendas */
  podium_trophy: Trophy,
  podium_medal: Medal,
};
