// ======================================================
// ICON REGISTRY: S7
// Objetivo:
// - Centralizar o mapeamento de ícones do Design System
// ======================================================

import {
  LayoutDashboard,
  Box,
  Tag,
  Calculator,
  Activity,
  BarChart3,
  FileText,
  Download,
  Copy,
  ExternalLink,
  GripVertical,
  Trash2,
  Info,
  Plus,
  Image as ImageIcon,
  Inbox,
  LayoutGrid,
  CircleAlert,
  Percent,
  Flame,
  CircleDollarSign,
  PackageX,
  Boxes,
  MegaphoneOff,
  Store,
  Megaphone,
  Receipt,
  TriangleAlert,
  Sparkles,
  LineChart,
  Clock,
  RotateCcw,
  Search,
  X,
  Eye,
} from "lucide-react";

export const iconsMap = {
  dashboard: LayoutDashboard,
  products: Box,
  ads: Tag,
  pricing: Calculator,
  monitoring: Activity,
  reports: BarChart3,
  records: FileText,

  download: Download,
  copy: Copy,
  external: ExternalLink,
  reorder: GripVertical,
  trash: Trash2,
  info: Info,
  plus: Plus,
  image: ImageIcon,
  empty: Inbox,

  /** Catálogo de produtos — barra de filtros (lucide, traço leve no JSX) */
  catalog_filter_all: LayoutGrid,
  catalog_filter_loss: CircleAlert,
  catalog_filter_low_margin: Percent,
  catalog_filter_top_sales: Flame,
  catalog_filter_top_profit: CircleDollarSign,
  catalog_filter_no_sales: PackageX,
  catalog_filter_low_stock: Boxes,
  catalog_filter_no_ads: MegaphoneOff,
  catalog_filter_mkt: Store,
  catalog_filter_with_ads: Megaphone,
  catalog_filter_with_sales: Receipt,
  catalog_filter_attention: TriangleAlert,
  catalog_filter_opportunity: Sparkles,
  catalog_filter_declining: LineChart,
  catalog_filter_new: Clock,
  /** Anúncios — filtro por volume de visitas */
  ads_filter_visits: Eye,
  filter_clear: RotateCcw,
  search: Search,
  close: X,
};
